changes to install scripts based on FOGL-2965
foglamp/foglamp-south-wind-turbine pull request #4
Opened 2019-07-02 17:50 UTC by oshadmon

Broke-down `requirements.sh` to `requirements.sh` and `extras_install.sh`  based on [FOGL-2965](https://scaledb.atlassian.net/browse/FOGL-2965).

2019-07-02 18:11 UTC, ashish-jabble requested changes

2019-07-02 18:11 UTC, ashish-jabble commented on requirements.sh
> +## ./extras_install
Uncomment the code line; as we need this when non-package installation is required.

2019-07-08 18:40 UTC, oshadmon reviewed
LGTM

2019-08-06 15:37 UTC, ashish-jabble commented
@praveen-garg Kindly review.

2019-08-06 15:41 UTC, praveen-garg approved these changes
lgtm! I believe you have already executed `chmod +x extras_install.sh` Hence `./extras_install.sh`

2019-08-06 15:41 UTC, ashish-jabble approved these changes

2019-08-06 15:42 UTC, merged